/*
 * HamsterErrorCodes.h
 *
 *  Created on: Sep 25, 2016
 *      Author: ofir
 */

#ifndef HAMSTERAPICOMMON_INCLUDE_HAMSTERAPICOMMON_COMMON_HAMSTERERRORCODES_H_
#define HAMSTERAPICOMMON_INCLUDE_HAMSTERAPICOMMON_COMMON_HAMSTERERRORCODES_H_

namespace HamsterAPI
{
	#define ERROR_CODE_NONE 0
	#define ERROR_CODE_MESSAGE_NOT_INITIALIZED 1
	#define ERROR_CODE_NO_MESSAGES 2
	#define ERROR_CODE_NO_CONNECTION 3
	#define ERROR_CODE_INVALID_MESSAGE 4
	#define ERROR_CODE_HANDSHAKE_FAILURE 5
	#define ERROR_CODE_CONNECTION_ERROR 6
	#define ERROR_CODE_INVALID_VERSION 7
	#define ERROR_CODE_GOAL_FAILURE 8
	#define ERROR_CODE_REQUEST_TIMEOUT 9
	#define ERROR_CODE_GOAL_IN_PROGRESS 10
	#define ERROR_CODE_MESSAGE_CUSTOM 100

	static std::string errorCodeToString(int error_code)
	{
		switch(error_code)
		{
			case ERROR_CODE_NONE:
				return "ERROR_CODE_NONE";
			case ERROR_CODE_MESSAGE_NOT_INITIALIZED:
				return "ERROR_CODE_MESSAGE_NOT_INITIALIZED";
			case ERROR_CODE_NO_MESSAGES:
				return "ERROR_CODE_NO_MESSAGES";
			case ERROR_CODE_NO_CONNECTION:
				return "ERROR_CODE_NO_CONNECTION";
			case ERROR_CODE_INVALID_MESSAGE:
				return "ERROR_CODE_INVALID_MESSAGE";
			case ERROR_CODE_HANDSHAKE_FAILURE:
				return "ERROR_CODE_HANDSHAKE_FAILURE";
			case ERROR_CODE_CONNECTION_ERROR:
				return "ERROR_CODE_CONNECTION_ERROR";
			case ERROR_CODE_INVALID_VERSION:
				return "ERROR_CODE_INVALID_VERSION";
			case ERROR_CODE_GOAL_FAILURE:
				return "ERROR_CODE_GOAL_FAILURE";
			case ERROR_CODE_REQUEST_TIMEOUT:
				return "ERROR_CODE_REQUEST_TIMEOUT";
			case ERROR_CODE_GOAL_IN_PROGRESS:
				return "ERROR_CODE_GOAL_IN_PROGRESS";
			default:
				return "ERROR_CODE_CUSTOM";
		}
	}
}




#endif /* HAMSTERAPICOMMON_INCLUDE_HAMSTERAPICOMMON_COMMON_HAMSTERERRORCODES_H_ */
